from __future__ import annotations

from math import floor
import os
from pathlib import Path


_BMS_DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def relative_sample_prefix(export_path: str | Path, sample_dir: str | Path | None) -> str:
    """Return a BMS-safe relative directory prefix for representative WAVs."""
    if sample_dir is None:
        return ""
    base = Path(export_path).resolve().parent
    target = Path(sample_dir).resolve()
    relative = os.path.relpath(target, base)
    if relative in {".", ""}:
        return ""
    return Path(relative).as_posix().rstrip("/") + "/"


def _bms_code(value: int) -> str:
    """Encode a positive sample id as the two-character BMS base-36 code."""
    value = max(1, int(value))
    if value >= 36 * 36:
        raise ValueError("BMS supports at most 1295 key-sound ids")
    return _BMS_DIGITS[value // 36] + _BMS_DIGITS[value % 36]


def _sample_number(sample_id: str, fallback: int) -> int:
    try:
        return int(str(sample_id).rsplit("_", 1)[-1])
    except (TypeError, ValueError):
        return int(fallback)


def _sample_filename(prefix: str, sample_number: int) -> str:
    prefix = str(prefix or "")
    if prefix.endswith("_") and "/" not in prefix and "\\" not in prefix:
        return f"{prefix}{sample_number:03d}.wav"
    directory = Path(prefix.replace("\\", "/")).as_posix().rstrip("/")
    return f"{directory + '/' if directory and directory != '.' else ''}sample_{sample_number:03d}.wav"


def _event_positions(events, *, bpm: float, offset: float, subdivision: int) -> tuple[dict, list[str]]:
    if bpm <= 0:
        raise ValueError("bpm must be positive")
    slots = max(4, int(subdivision) * 4)
    measure_seconds = 240.0 / float(bpm)
    placed: dict[tuple[int, int], dict] = {}
    warnings: list[str] = []
    for event in events:
        time = float(event.get("time", 0.0))
        relative = (time - float(offset)) / measure_seconds
        if relative < 0:
            warnings.append(f"時刻{time:.6f}s: グリッド開始より前のため先頭へ配置")
            relative = 0.0
        measure = int(floor(relative))
        slot = round((relative - measure) * slots)
        if slot >= slots:
            measure += slot // slots
            slot %= slots
        key = (measure, slot)
        if key in placed:
            warnings.append(f"時刻{time:.6f}s: 同一グリッドに複数ノートがあるため後続を省略")
            continue
        placed[key] = event
    return placed, warnings


def write_bms(
    path: str | Path,
    plan,
    *,
    wav_prefix: str = "sample_",
    bpm: float | None = None,
    offset: float = 0.0,
    subdivision: int = 16,
    channel: str = "01",
    title: str = "BMS Stem Reuse",
    excluded_hits: set[int] | None = None,
) -> Path:
    """Write actual BMS key-sound events on channel 01.

    Gain variants remain explicitly documented because standard BMS has no
    event-level gain field; users can bake them as separate WAVs later.
    """
    if bpm is None or bpm <= 0:
        raise ValueError("BMS出力にはBPMが必要です")
    channel = str(channel).strip()
    if len(channel) != 2 or any(char not in "0123456789" for char in channel):
        raise ValueError("BMSチャンネルは2桁の数字で指定してください")
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "; Generated by BMS Stem Reuse Analyzer",
        f"#TITLE {title}",
        "#PLAYER 1",
        f"#BPM {float(bpm):.6f}".rstrip("0").rstrip("."),
        f"; Event channel: {channel} ({'BGM' if channel == '01' else '1P key-sound' if channel.startswith('1') else 'custom'})",
    ]
    if channel == "01":
        lines.append("; WARNING: channel 01 is BGM-compatible; use channel 11+ for playable key lanes.")
    for cluster in plan.clusters:
        lines.append(f"#WAV{_bms_code(cluster.id)} {_sample_filename(wav_prefix, cluster.id)}")
    events = [event for event in plan.events if not excluded_hits or int(event.get("hit", -1)) not in excluded_hits]
    placed, warnings = _event_positions(events, bpm=bpm, offset=offset, subdivision=subdivision)
    slots = max(4, int(subdivision) * 4)
    for measure in sorted({key[0] for key in placed}):
        tokens = ["00"] * slots
        for (event_measure, slot), event in placed.items():
            if event_measure != measure:
                continue
            sample_number = _sample_number(event.get("sample_id", ""), 1)
            tokens[slot] = _bms_code(sample_number)
        lines.append(f"#{measure:03d}{channel}:{''.join(tokens)}")
    lines.append("; Gain variants are mapped to the same WAV; gain_db is kept in the BRA/CSV.")
    for event in events:
        gain = float(event.get("gain_db", 0.0))
        if abs(gain) >= 0.01:
            lines.append(f"; GAIN_VARIANT {event.get('time', 0.0):.6f}s {event.get('sample_id', '')} {gain:+.4f}dB")
    for warning in warnings:
        lines.append(f"; GRID_WARNING {warning}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
