from __future__ import annotations

from pathlib import Path


def write_bms(path: str | Path, plan, *, wav_prefix: str = "sample_") -> Path:
    """Write the reusable sample declarations and a comment-only event map."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["; Generated by BMS Stem Reuse Analyzer", "#PLAYER 1", "#BPM 120"]
    for cluster in plan.clusters:
        lines.append(f"#WAV{cluster.id:02X} {wav_prefix}{cluster.id:03d}.wav")
    lines.append("; Event mapping (time/sample/gain dB):")
    lines.extend(f"; {event['time']:.6f} {event['sample_id']} {event['gain_db']:.4f}" for event in plan.events)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
